openapi: 3.0.0
info:
  title: S2S RNG API
  version: 1.0.0
  description: Szrek2Solutions Random Number Generator API
  contact:
    url: 'http://www.szrek.com'
servers:
  - url: 'http://localhost:55002/s2s-rng-api/v1.0'
paths:
  /draws/regular-draws:
    post:
      summary: ''
      operationId: post-draws-regular-draws
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  clientTransactionId:
                    type: string
                    description: Client's unique ID for this transaction
                  transactionStatus:
                    $ref: '#/components/schemas/Status'
                  serverId:
                    type: string
                    example: RNG-TEST-87
                    description: RNG server identifier
                  serverVersion:
                    type: string
                    example: '9.3'
                    description: RNG server version number
                  serverTime:
                    type: string
                    format: date-time
                    example: '2020-09-30T18:30:23Z'
                    description: Current system time of the RNG server
                  rngBusinessDay:
                    type: integer
                    description: Business day under which the transaction was recorded. Format is YYMMDD.
                    example: 200930
                  testMode:
                    type: boolean
                    description: Marks the draw results as "test mode" and not valid for use
                  drawResults:
                    type: array
                    description: 'Array of results objects, corresponding to array of requests'
                    items:
                      type: object
                      properties:
                        clientRequestId:
                          type: string
                          description: Client's unique identifier for this draw request
                          example: RQID-31234545-32
                        drawStatus:
                          $ref: '#/components/schemas/Status'
                        productId:
                          type: integer
                          description: Identifier of the product definition drawn
                        drawMatrix:
                          $ref: '#/components/schemas/DrawMatrix'
                        distribution:
                          $ref: '#/components/schemas/Distribution'
                        drawTime:
                          type: string
                          format: date-time
                          description: Timestamp of the draw
                          example: '2020-09-30T18:30:23Z'
                        recordId:
                          type: string
                          description: Unique record identifier for the draw
                          example: EX191109870000000125
                        recordHandle:
                          type: integer
                          description: Handle that can optionally be used for faster verification processing
                          format: int64
                        sets:
                          type: array
                          description: Numbers drawn
                          items:
                            type: array
                            items:
                              type: integer
                      required:
                        - drawStatus
              examples:
                Minimal Example:
                  value:
                    transactionStatus:
                      code: 0
                      description: Success
                    serverId: RNG-TEST-87
                    serverVersion: '9.3'
                    serverTime: '2020-09-30T18:30:23Z'
                    rngBusinessDay: 200930
                    testMode: false
                    drawResults:
                      - drawStatus:
                          code: 0
                          description: Success
                        productId: 1002
                        numberOfSets: 1
                        drawMatrix:
                          setSize: 6
                          minValue: 1
                          maxValue: 49
                          withReplacement: true
                        drawTime: '2020-09-30T18:30:23Z'
                        recordId: EX191109870000000125
                        recordHandle: -1
                        sets:
                          - - 9
                            - 16
                            - 26
                            - 29
                            - 37
                            - 42
                Example:
                  value:
                    clientTransactionId: TXID-102030450-11
                    transactionStatus:
                      code: 0
                      description: Success
                    serverId: RNG-TEST-87
                    serverVersion: '9.3'
                    serverTime: '2020-09-30T18:30:23Z'
                    rngBusinessDay: 200930
                    testMode: true
                    drawResults:
                      - clientRequestId: RQID-31234545-32
                        drawStatus:
                          code: 0
                          description: Success
                        productId: 1006
                        numberOfSets: 2
                        drawMatrix:
                          setSize: 5
                          minValue: 1
                          maxValue: 39
                          withReplacement: true
                        drawTime: '2020-09-30T18:30:23Z'
                        recordId: EX191109870000000125
                        recordHandle: 43543
                        sets:
                          - - 10
                            - 21
                            - 29
                            - 35
                            - 39
                          - - 3
                            - 8
                            - 17
                            - 22
                            - 34
        '400':
          description: Bad Request
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Example:
                  value:
                    status:
                      code: 999
                      description: Input validation failed
                    fieldErrors:
                      - code: INVALID_VALUE
                        message: Product not found
                        fieldName: productId
                        path: 'drawRequests[1].productId'
      description: Create draws for regular draw products
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                clientTransactionId:
                  type: string
                  description: Client's unique ID for this transaction
                  format: int64
                  example: TXID-102030450-11
                clientBusinessDay:
                  type: integer
                  description: Client's current business day. Format is YYMMDD.
                  example: 200930
                testMode:
                  type: boolean
                  description: Marks the draw results as "test mode" and not valid for use
                drawUsers:
                  type: array
                  description: Draw personnel names and login times to be included in the draw reports
                  items:
                    $ref: '#/components/schemas/DrawUsers'
                drawRequests:
                  type: array
                  description: One or more draw requests to be processed
                  items:
                    type: object
                    properties:
                      clientRequestId:
                        type: string
                        description: Client's unique identifier for this draw request
                        example: RQID-31234545-32
                      drawText:
                        type: string
                        description: An extra text string that will appear in the draw reports and is also appended to the draw report file names
                        example: PROMO-1
                      drawHash:
                        type: string
                        description: 'A hash string that will be included in the signed data, such as the SHA-1 hash of the bets'
                        format: binary
                      drawNumber:
                        type: integer
                        description: Number to assign to this draw. Shown in draw reports and file names
                        example: 364
                      productId:
                        type: integer
                        description: 'Identifier of the product definition to be drawn. The product defines all draw parameters, and MAY allow them to be overridden with the parameters below.'
                      numberOfSets:
                        type: integer
                        description: How many sets of numbers to draw
                      drawMatrix:
                        $ref: '#/components/schemas/DrawMatrix'
                      distribution:
                        $ref: '#/components/schemas/Distribution'
                      extractData:
                        $ref: '#/components/schemas/ExtractData'
                    required:
                      - productId
                      - numberOfSets
              required:
                - drawRequests
            examples:
              Minimal Example:
                value:
                  drawRequests:
                    - productId: 1002
                      numberOfSets: 1
              Example:
                value:
                  clientTransactionId: TXID-102030450-11
                  clientBusinessDay: 200930
                  testMode: true
                  drawUsers:
                    - name: Jane Doe
                      loginTime: '2020-09-30T15:47:44Z'
                    - name: John Smith
                      loginTime: '2020-09-30T15:56:01Z'
                  drawRequests:
                    - clientRequestId: RQID-31234545-32
                      drawText: PROMO-1
                      drawHash: 9498A934974997B9723498A93D92498397BC70B
                      productId: 1006
                      numberOfSets: 2
                      drawMatrix:
                        setSize: 5
                        minValue: 1
                        maxValue: 39
                        withReplacement: true
                      extractData:
                        extractType: TYPE1
                        extractFields:
                          - '1234'
                          - ''
                          - '23485'
                          - ''
                          - ''
                          - 'true'
                          - '30.00'
        description: ''
      parameters: []
  /draws/quick-picks:
    post:
      summary: ''
      operationId: post-draws-quick-picks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  clientTransactionId:
                    type: string
                    description: Client's unique ID for this transaction
                  transactionStatus:
                    $ref: '#/components/schemas/Status'
                  serverId:
                    type: string
                    example: RNG-TEST-87
                    description: RNG server identifier
                  serverVersion:
                    type: string
                    example: '9.3'
                    description: RNG server version number
                  rngBusinessDay:
                    type: integer
                    description: Business day under which the transaction was recorded. Format is YYMMDD.
                    example: 200930
                  drawResults:
                    type: array
                    description: 'Array of results objects, corresponding to array of requests'
                    items:
                      type: object
                      properties:
                        clientRequestId:
                          type: string
                          description: Client's unique identifier for this draw request
                          example: RQID-31234545-32
                        drawStatus:
                          $ref: '#/components/schemas/Status'
                        productId:
                          type: integer
                          description: Identifier of the product definition drawn
                        drawTime:
                          type: string
                          format: date-time
                          description: Timestamp of the draw
                          example: '2020-09-30T18:30:23Z'
                        recordId:
                          type: string
                          description: Unique record identifier for the draw
                          example: EX191109870000000125
                        sets:
                          type: array
                          description: Numbers drawn
                          items:
                            type: array
                            items:
                              type: integer
                      required:
                        - drawStatus
                required:
                  - drawResults
              examples:
                Minimal Example:
                  value:
                    transactionStatus:
                      code: 0
                      description: Success
                    serverId: RNG-TEST-87
                    serverVersion: '9.3'
                    rngBusinessDay: 200930
                    drawResults:
                      - drawStatus:
                          code: 0
                          description: Success
                        productId: 1002
                        drawTime: '2020-09-30T18:30:23Z'
                        recordId: EX191109870000000125
                        sets:
                          - - 9
                            - 16
                            - 26
                            - 29
                            - 37
                            - 42
                Example:
                  value:
                    clientTransactionId: TXID-102030450-11
                    transactionStatus:
                      code: 0
                      description: Success
                    serverId: RNG-TEST-87
                    serverVersion: '9.3'
                    rngBusinessDay: 200930
                    drawResults:
                      - clientRequestId: RQID-31234545-32
                        drawStatus:
                          code: 0
                          description: Success
                        productId: 1006
                        drawTime: '2020-09-30T18:30:23Z'
                        recordId: EX191109870000000125
                        sets:
                          - - 10
                            - 21
                            - 29
                            - 35
                            - 39
                          - - 3
                            - 8
                            - 17
                            - 22
                            - 34
                      - clientRequestId: RQID-31234546-23
                        drawStatus:
                          code: 0
                          description: Success
                        productId: 1006
                        drawTime: '2020-09-30T18:30:23Z'
                        recordId: EX191109870000000254
                        sets:
                          - - 4
                            - 10
                            - 19
                            - 24
                            - 35
                            - 46
        '400':
          description: Bad Request
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Example:
                  value:
                    status:
                      code: 999
                      description: Input validation failed
                    fieldErrors:
                      - code: INVALID_VALUE
                        message: Product not found
                        fieldName: productId
                        path: 'drawRequests[1].productId'
      description: Create draws for quick pick products
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                clientTransactionId:
                  type: string
                  description: Client's unique ID for this transaction
                  format: int64
                  example: TXID-102030450-11
                clientBusinessDay:
                  type: integer
                  description: Client's current business day. Format is YYMMDD.
                  example: 200930
                drawRequests:
                  type: array
                  description: One or more draw requests to be processed
                  items:
                    type: object
                    properties:
                      clientRequestId:
                        type: string
                        description: Client's unique identifier for this draw request
                        example: RQID-31234545-32
                      productId:
                        type: integer
                        description: 'Identifier of the product definition to be drawn. The product defines all draw parameters, and MAY allow them to be overridden with the parameters below.'
                      numberOfSets:
                        type: integer
                        description: How many sets of numbers to draw
                      drawMatrix:
                        $ref: '#/components/schemas/DrawMatrix'
                      distribution:
                        $ref: '#/components/schemas/Distribution'
                    required:
                      - productId
                      - numberOfSets
              required:
                - drawRequests
            examples:
              Minimal Example:
                value:
                  drawRequests:
                    - productId: 1002
                      numberOfSets: 1
              Example:
                value:
                  clientTransactionId: TXID-102030450-11
                  clientBusinessDay: 200930
                  drawRequests:
                    - clientRequestId: RQID-31234545-32
                      productId: 1002
                      numberOfSets: 2
                      drawMatrix:
                        setSize: 5
                        minValue: 1
                        maxValue: 39
                        withReplacement: true
                    - clientRequestId: RQID-31234546-23
                      productId: 1006
                      numberOfSets: 1
                      drawMatrix:
                        setSize: 6
                        minValue: 1
                        maxValue: 49
                        withReplacement: true
        description: ''
      parameters: []
  /server/rng-status:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  serverId:
                    type: string
                    example: RNG-TEST-87
                    description: RNG server identifier
                  serverVersion:
                    type: string
                    example: '9.3'
                    description: RNG server version number
                  serverTime:
                    type: string
                    format: date-time
                    example: '2020-09-30T18:30:23Z'
                    description: Current system time of the RNG server
                  rngBusinessDay:
                    type: integer
                    description: Current business day for this RNG server. Format is YYMMDD.
                    example: 200930
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        type:
                          type: string
                        requestCount:
                          type: string
                        lastRequestTime:
                          type: string
                  cards:
                    type: string
      operationId: get-server-status
      description: Get current status of the RNG server and the configured products
    parameters: []
components:
  schemas:
    DrawUsers:
      title: DrawUsers
      type: object
      description: 'Draw personnel to be included in the draw reports. The first user is the Draw Manager, second user is the Draw Auditor, and third is the Draw Observer.'
      properties:
        name:
          type: string
          description: Full name of the user as it should appear in the draw reports
          example: John Smith
        loginTime:
          type: string
          format: date-time
          description: 'If included, the login time for the user will appear in the draw reports'
          example: '2020-03-15T15:47:44Z'
    DrawMatrix:
      title: DrawMatrix
      type: object
      description: The RNG draw parameter matrix. The product definition may or may not allow overriding of these values
      properties:
        setSize:
          type: integer
          description: How many numbers in each set
          example: 6
        minValue:
          type: integer
          description: Lowest number that can be drawn
          example: 1
        maxValue:
          type: integer
          description: Highest number that can be drawn
          example: 49
        withReplacement:
          type: boolean
          description: Specifies whether drawn numbers are replaced within a set
        exclusions:
          type: array
          description: Values to be excluded from the draw
          uniqueItems: true
          items:
            type: integer
            example: 0
    Distribution:
      title: Distribution
      type: object
      description: Initial distribution values and depletion type used for distribution-type products
      properties:
        values:
          type: array
          description: Initial distribution values
          items:
            type: integer
        depletionType:
          type: string
          enum:
            - NoDepletion
            - DecreaseEntry
            - RemoveEntry
          description: Specifies method of depletion for the distribution values
          example: NoDepletion
    ExtractData:
      title: ExtractData
      type: object
      description: Optional data passed through to the audit process and optionally included in CSV extract files it creates
      properties:
        extractType:
          type: string
          description: Used to define the CSV extract report options
        extractFields:
          type: array
          description: Positional data values that can be included in the CSV extract files. Field positions must be the same for all draws using the same extract type
          items:
            type: string
    Status:
      title: Status
      type: object
      description: Status code and description
      properties:
        code:
          type: integer
          description: Numeric error or status code
        description:
          type: string
          description: Short description of the error or status code
    FieldError:
      title: FieldError
      type: object
      description: Details about a specific field error
      properties:
        code:
          type: string
          description: Error code name
        message:
          type: string
          description: Additional detail about the error code
        fieldName:
          type: string
          description: 'Name of the field that caused the error, if applicable'
        path:
          type: string
          description: 'Path to the field that caused the error, if applicable'
    Error:
      title: Error
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Status'
        fieldErrors:
          type: array
          items:
            $ref: '#/components/schemas/FieldError'
security: []
